### ISSUE TITLE
@xiaming   --feedback  

### ISSUE THREAD

**Issue by shawn-xia** [Iodachi/Revive#1]
1. The transition between intro level and level 2 is not smoothy enough.  
2. The scale of level2 is a lot bigger than the intro one, and speed of player's movement and jump is slower than that of in the intro level.

**Comment by Iodachi** [comment]
The game is currently having an empty space in intro level to make the transition to level 2 happen, will consider adding a sign or npc to talk with to introduce to the next level.
Fixed some configurations including player's size, movement speed, jump height etc, to get used to the different scale in level 2.
